/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ViewLayout } from "./utils/breakpoints";
import { IconName } from "./blocks/icon/icon.component";
import { Map } from "maplibre-gl";
import { LayerConfig, PopupDefinition } from "./blocks/map-layer-base-odh/noi-map-layer-base-odh.component";
import { SelectOption } from "./blocks/select/select.component";
export { ViewLayout } from "./utils/breakpoints";
export { IconName } from "./blocks/icon/icon.component";
export { Map } from "maplibre-gl";
export { LayerConfig, PopupDefinition } from "./blocks/map-layer-base-odh/noi-map-layer-base-odh.component";
export { SelectOption } from "./blocks/select/select.component";
export namespace Components {
    /**
     * (INTERNAL) render a checkbox
     */
    interface NoiCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
    }
    /**
     * (INTERNAL) render a checkbox group
     */
    interface NoiCheckboxGroup {
        /**
          * @default false
         */
        "open": boolean;
    }
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface NoiDigiway {
        /**
          * Base map layer
          * @default 'tirol'
         */
        "baseMap": 'osm' | 'tirol';
        /**
          * Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap": string;
        /**
          * Language
          * @default 'en'
         */
        "language": string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout": ViewLayout;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name": IconName | string;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface NoiMap {
        /**
          * Map center. Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap": string;
        "getMapAsync": () => Promise<Map>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseOsm {
        /**
          * @default 'color'
         */
        "variant": 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseTirol {
        /**
          * @default 'color'
         */
        "variant": 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerAnnouncements {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerBaseOdh {
        "config": LayerConfig;
        "popupStructure"?: ((feature: any, featureType: string) => PopupDefinition | string);
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerCyclingRoads {
        "region": 'tyrol' | 'bolzano-prov' | 'bolzano-int' | 'trento' | 'mountainbikeroutes' | 'mtb_percorsi_v';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRiskExposure {
    }
    /**
     * (INTERNAL) render a select box
     */
    interface NoiSelect {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        "options": SelectOption[];
        /**
          * @default null
         */
        "value": string;
    }
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiSpinner {
    }
}
export interface NoiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiCheckboxElement;
}
export interface NoiMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapElement;
}
export interface NoiMapLayerAnnouncementsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerAnnouncementsElement;
}
export interface NoiMapLayerBaseOdhCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerBaseOdhElement;
}
export interface NoiMapLayerCyclingRoadsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerCyclingRoadsElement;
}
export interface NoiMapLayerRiskExposureCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerRiskExposureElement;
}
export interface NoiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiSelectElement;
}
declare global {
    interface HTMLNoiCheckboxElementEventMap {
        "checkedChange": { checked: boolean };
    }
    /**
     * (INTERNAL) render a checkbox
     */
    interface HTMLNoiCheckboxElement extends Components.NoiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiCheckboxElementEventMap>(type: K, listener: (this: HTMLNoiCheckboxElement, ev: NoiCheckboxCustomEvent<HTMLNoiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiCheckboxElementEventMap>(type: K, listener: (this: HTMLNoiCheckboxElement, ev: NoiCheckboxCustomEvent<HTMLNoiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiCheckboxElement: {
        prototype: HTMLNoiCheckboxElement;
        new (): HTMLNoiCheckboxElement;
    };
    /**
     * (INTERNAL) render a checkbox group
     */
    interface HTMLNoiCheckboxGroupElement extends Components.NoiCheckboxGroup, HTMLStencilElement {
    }
    var HTMLNoiCheckboxGroupElement: {
        prototype: HTMLNoiCheckboxGroupElement;
        new (): HTMLNoiCheckboxGroupElement;
    };
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface HTMLNoiDigiwayElement extends Components.NoiDigiway, HTMLStencilElement {
    }
    var HTMLNoiDigiwayElement: {
        prototype: HTMLNoiDigiwayElement;
        new (): HTMLNoiDigiwayElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLNoiMapElementEventMap {
        "mapReady": Map;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface HTMLNoiMapElement extends Components.NoiMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapElement: {
        prototype: HTMLNoiMapElement;
        new (): HTMLNoiMapElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapBaseOsmElement extends Components.NoiMapBaseOsm, HTMLStencilElement {
    }
    var HTMLNoiMapBaseOsmElement: {
        prototype: HTMLNoiMapBaseOsmElement;
        new (): HTMLNoiMapBaseOsmElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapBaseTirolElement extends Components.NoiMapBaseTirol, HTMLStencilElement {
    }
    var HTMLNoiMapBaseTirolElement: {
        prototype: HTMLNoiMapBaseTirolElement;
        new (): HTMLNoiMapBaseTirolElement;
    };
    interface HTMLNoiMapLayerAnnouncementsElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerAnnouncementsElement extends Components.NoiMapLayerAnnouncements, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerAnnouncementsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerAnnouncementsElement, ev: NoiMapLayerAnnouncementsCustomEvent<HTMLNoiMapLayerAnnouncementsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerAnnouncementsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerAnnouncementsElement, ev: NoiMapLayerAnnouncementsCustomEvent<HTMLNoiMapLayerAnnouncementsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerAnnouncementsElement: {
        prototype: HTMLNoiMapLayerAnnouncementsElement;
        new (): HTMLNoiMapLayerAnnouncementsElement;
    };
    interface HTMLNoiMapLayerBaseOdhElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerBaseOdhElement extends Components.NoiMapLayerBaseOdh, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerBaseOdhElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerBaseOdhElement, ev: NoiMapLayerBaseOdhCustomEvent<HTMLNoiMapLayerBaseOdhElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerBaseOdhElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerBaseOdhElement, ev: NoiMapLayerBaseOdhCustomEvent<HTMLNoiMapLayerBaseOdhElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerBaseOdhElement: {
        prototype: HTMLNoiMapLayerBaseOdhElement;
        new (): HTMLNoiMapLayerBaseOdhElement;
    };
    interface HTMLNoiMapLayerCyclingRoadsElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerCyclingRoadsElement extends Components.NoiMapLayerCyclingRoads, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerCyclingRoadsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerCyclingRoadsElement, ev: NoiMapLayerCyclingRoadsCustomEvent<HTMLNoiMapLayerCyclingRoadsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerCyclingRoadsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerCyclingRoadsElement, ev: NoiMapLayerCyclingRoadsCustomEvent<HTMLNoiMapLayerCyclingRoadsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerCyclingRoadsElement: {
        prototype: HTMLNoiMapLayerCyclingRoadsElement;
        new (): HTMLNoiMapLayerCyclingRoadsElement;
    };
    interface HTMLNoiMapLayerRiskExposureElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerRiskExposureElement extends Components.NoiMapLayerRiskExposure, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerRiskExposureElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRiskExposureElement, ev: NoiMapLayerRiskExposureCustomEvent<HTMLNoiMapLayerRiskExposureElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerRiskExposureElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRiskExposureElement, ev: NoiMapLayerRiskExposureCustomEvent<HTMLNoiMapLayerRiskExposureElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerRiskExposureElement: {
        prototype: HTMLNoiMapLayerRiskExposureElement;
        new (): HTMLNoiMapLayerRiskExposureElement;
    };
    interface HTMLNoiSelectElementEventMap {
        "selectChange": string;
    }
    /**
     * (INTERNAL) render a select box
     */
    interface HTMLNoiSelectElement extends Components.NoiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiSelectElementEventMap>(type: K, listener: (this: HTMLNoiSelectElement, ev: NoiSelectCustomEvent<HTMLNoiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiSelectElementEventMap>(type: K, listener: (this: HTMLNoiSelectElement, ev: NoiSelectCustomEvent<HTMLNoiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiSelectElement: {
        prototype: HTMLNoiSelectElement;
        new (): HTMLNoiSelectElement;
    };
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiSpinnerElement extends Components.NoiSpinner, HTMLStencilElement {
    }
    var HTMLNoiSpinnerElement: {
        prototype: HTMLNoiSpinnerElement;
        new (): HTMLNoiSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "noi-checkbox": HTMLNoiCheckboxElement;
        "noi-checkbox-group": HTMLNoiCheckboxGroupElement;
        "noi-digiway": HTMLNoiDigiwayElement;
        "noi-icon": HTMLNoiIconElement;
        "noi-map": HTMLNoiMapElement;
        "noi-map-base-osm": HTMLNoiMapBaseOsmElement;
        "noi-map-base-tirol": HTMLNoiMapBaseTirolElement;
        "noi-map-layer-announcements": HTMLNoiMapLayerAnnouncementsElement;
        "noi-map-layer-base-odh": HTMLNoiMapLayerBaseOdhElement;
        "noi-map-layer-cycling-roads": HTMLNoiMapLayerCyclingRoadsElement;
        "noi-map-layer-risk-exposure": HTMLNoiMapLayerRiskExposureElement;
        "noi-select": HTMLNoiSelectElement;
        "noi-spinner": HTMLNoiSpinnerElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * (INTERNAL) render a checkbox
     */
    interface NoiCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onCheckedChange"?: (event: NoiCheckboxCustomEvent<{ checked: boolean }>) => void;
    }
    /**
     * (INTERNAL) render a checkbox group
     */
    interface NoiCheckboxGroup {
        /**
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface NoiDigiway {
        /**
          * Base map layer
          * @default 'tirol'
         */
        "baseMap"?: 'osm' | 'tirol';
        /**
          * Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        /**
          * Language
          * @default 'en'
         */
        "language"?: string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout"?: ViewLayout;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface NoiMap {
        /**
          * Map center. Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        /**
          * Emitted when map is initialized and ready to draw on it
         */
        "onMapReady"?: (event: NoiMapCustomEvent<Map>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseOsm {
        /**
          * @default 'color'
         */
        "variant"?: 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseTirol {
        /**
          * @default 'color'
         */
        "variant"?: 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerAnnouncements {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerAnnouncementsCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerBaseOdh {
        "config": LayerConfig;
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerBaseOdhCustomEvent<boolean>) => void;
        "popupStructure"?: ((feature: any, featureType: string) => PopupDefinition | string);
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerCyclingRoads {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerCyclingRoadsCustomEvent<boolean>) => void;
        "region": 'tyrol' | 'bolzano-prov' | 'bolzano-int' | 'trento' | 'mountainbikeroutes' | 'mtb_percorsi_v';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRiskExposure {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerRiskExposureCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render a select box
     */
    interface NoiSelect {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onSelectChange"?: (event: NoiSelectCustomEvent<string>) => void;
        "options"?: SelectOption[];
        /**
          * @default null
         */
        "value"?: string;
    }
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiSpinner {
    }

    interface NoiCheckboxAttributes {
        "disabled": boolean;
        "checked": boolean;
        "loading": boolean;
    }
    interface NoiCheckboxGroupAttributes {
        "open": boolean;
    }
    interface NoiDigiwayAttributes {
        "layout": ViewLayout;
        "baseMap": 'osm' | 'tirol';
        "centermap": string;
        "language": string;
    }
    interface NoiIconAttributes {
        "name": IconName | string;
    }
    interface NoiMapAttributes {
        "centermap": string;
    }
    interface NoiMapBaseOsmAttributes {
        "variant": 'color' | 'grayscale';
    }
    interface NoiMapBaseTirolAttributes {
        "variant": 'color' | 'grayscale';
    }
    interface NoiMapLayerCyclingRoadsAttributes {
        "region": 'tyrol' | 'bolzano-prov' | 'bolzano-int' | 'trento' | 'mountainbikeroutes' | 'mtb_percorsi_v';
    }
    interface NoiSelectAttributes {
        "disabled": boolean;
        "value": string;
    }

    interface IntrinsicElements {
        "noi-checkbox": Omit<NoiCheckbox, keyof NoiCheckboxAttributes> & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes]?: NoiCheckbox[K] } & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes as `attr:${K}`]?: NoiCheckboxAttributes[K] } & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes as `prop:${K}`]?: NoiCheckbox[K] };
        "noi-checkbox-group": Omit<NoiCheckboxGroup, keyof NoiCheckboxGroupAttributes> & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes]?: NoiCheckboxGroup[K] } & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes as `attr:${K}`]?: NoiCheckboxGroupAttributes[K] } & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes as `prop:${K}`]?: NoiCheckboxGroup[K] };
        "noi-digiway": Omit<NoiDigiway, keyof NoiDigiwayAttributes> & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes]?: NoiDigiway[K] } & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes as `attr:${K}`]?: NoiDigiwayAttributes[K] } & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes as `prop:${K}`]?: NoiDigiway[K] };
        "noi-icon": Omit<NoiIcon, keyof NoiIconAttributes> & { [K in keyof NoiIcon & keyof NoiIconAttributes]?: NoiIcon[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `attr:${K}`]?: NoiIconAttributes[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `prop:${K}`]?: NoiIcon[K] };
        "noi-map": Omit<NoiMap, keyof NoiMapAttributes> & { [K in keyof NoiMap & keyof NoiMapAttributes]?: NoiMap[K] } & { [K in keyof NoiMap & keyof NoiMapAttributes as `attr:${K}`]?: NoiMapAttributes[K] } & { [K in keyof NoiMap & keyof NoiMapAttributes as `prop:${K}`]?: NoiMap[K] };
        "noi-map-base-osm": Omit<NoiMapBaseOsm, keyof NoiMapBaseOsmAttributes> & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes]?: NoiMapBaseOsm[K] } & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes as `attr:${K}`]?: NoiMapBaseOsmAttributes[K] } & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes as `prop:${K}`]?: NoiMapBaseOsm[K] };
        "noi-map-base-tirol": Omit<NoiMapBaseTirol, keyof NoiMapBaseTirolAttributes> & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes]?: NoiMapBaseTirol[K] } & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes as `attr:${K}`]?: NoiMapBaseTirolAttributes[K] } & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes as `prop:${K}`]?: NoiMapBaseTirol[K] };
        "noi-map-layer-announcements": NoiMapLayerAnnouncements;
        "noi-map-layer-base-odh": NoiMapLayerBaseOdh;
        "noi-map-layer-cycling-roads": Omit<NoiMapLayerCyclingRoads, keyof NoiMapLayerCyclingRoadsAttributes> & { [K in keyof NoiMapLayerCyclingRoads & keyof NoiMapLayerCyclingRoadsAttributes]?: NoiMapLayerCyclingRoads[K] } & { [K in keyof NoiMapLayerCyclingRoads & keyof NoiMapLayerCyclingRoadsAttributes as `attr:${K}`]?: NoiMapLayerCyclingRoadsAttributes[K] } & { [K in keyof NoiMapLayerCyclingRoads & keyof NoiMapLayerCyclingRoadsAttributes as `prop:${K}`]?: NoiMapLayerCyclingRoads[K] } & OneOf<"region", NoiMapLayerCyclingRoads["region"], NoiMapLayerCyclingRoadsAttributes["region"]>;
        "noi-map-layer-risk-exposure": NoiMapLayerRiskExposure;
        "noi-select": Omit<NoiSelect, keyof NoiSelectAttributes> & { [K in keyof NoiSelect & keyof NoiSelectAttributes]?: NoiSelect[K] } & { [K in keyof NoiSelect & keyof NoiSelectAttributes as `attr:${K}`]?: NoiSelectAttributes[K] } & { [K in keyof NoiSelect & keyof NoiSelectAttributes as `prop:${K}`]?: NoiSelect[K] };
        "noi-spinner": NoiSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * (INTERNAL) render a checkbox
             */
            "noi-checkbox": LocalJSX.IntrinsicElements["noi-checkbox"] & JSXBase.HTMLAttributes<HTMLNoiCheckboxElement>;
            /**
             * (INTERNAL) render a checkbox group
             */
            "noi-checkbox-group": LocalJSX.IntrinsicElements["noi-checkbox-group"] & JSXBase.HTMLAttributes<HTMLNoiCheckboxGroupElement>;
            /**
             * Consolidated web-component to show Open Data Hub data imported within the Digiway project
             */
            "noi-digiway": LocalJSX.IntrinsicElements["noi-digiway"] & JSXBase.HTMLAttributes<HTMLNoiDigiwayElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.IntrinsicElements["noi-icon"] & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
            /**
             * (INTERNAL) render a basic map with no layouts
             */
            "noi-map": LocalJSX.IntrinsicElements["noi-map"] & JSXBase.HTMLAttributes<HTMLNoiMapElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-base-osm": LocalJSX.IntrinsicElements["noi-map-base-osm"] & JSXBase.HTMLAttributes<HTMLNoiMapBaseOsmElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-base-tirol": LocalJSX.IntrinsicElements["noi-map-base-tirol"] & JSXBase.HTMLAttributes<HTMLNoiMapBaseTirolElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-announcements": LocalJSX.IntrinsicElements["noi-map-layer-announcements"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerAnnouncementsElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-base-odh": LocalJSX.IntrinsicElements["noi-map-layer-base-odh"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerBaseOdhElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-cycling-roads": LocalJSX.IntrinsicElements["noi-map-layer-cycling-roads"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerCyclingRoadsElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-risk-exposure": LocalJSX.IntrinsicElements["noi-map-layer-risk-exposure"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerRiskExposureElement>;
            /**
             * (INTERNAL) render a select box
             */
            "noi-select": LocalJSX.IntrinsicElements["noi-select"] & JSXBase.HTMLAttributes<HTMLNoiSelectElement>;
            /**
             * (INTERNAL) render a apinner.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-spinner": LocalJSX.IntrinsicElements["noi-spinner"] & JSXBase.HTMLAttributes<HTMLNoiSpinnerElement>;
        }
    }
}
